<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ProgrammingInCSharpStore.DAL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProgrammingInCSharpStore.MyWindowsformApp.Domain\ProgrammingInCSharpStore.MyWindowsformApp.Domain.csproj" />
  </ItemGroup>

</Project>
