<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ProgrammingInCSharpStore.Business</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProgrammingInCSharpStore.MyWindowsformApp.DAL\ProgrammingInCSharpStore.MyWindowsformApp.DAL.csproj" />
  </ItemGroup>

</Project>
